version: '3.3'
services:
    animetarr:
        container_name: animetarr
        ports:
            - '3000:3000/tcp'
        environment:
            - API_PORT=3000
            - TVDB_API_KEY=YOURTVDBIDKEY
            - SONARR_API_BASE_URL='https://sonarr.home.host.local/api'
            - SONARR_API_KEY=YOURSONARRAPIKEY
            - SONARR_QUALITY_PROFILE_ID=3
            - SONARR_BASE_PATH=/downloads/anime/
            - PASSWORD=aLittleS3curity
        image: 'kariudo/animetarr:latest'