export const mockData = [
  {
    description:
      "Kimichika Haijima was a strong junior high school volleyball team member. After getting into trouble with the team, he moved to his mother's hometown and reunites with his childhood friend, Yuni Kuroba. The two become an ace pair at volleyball, but in their last tournament, get into a big fight. Will they ever play volleyball together again?",
    imageUrl:
      'https://www.thetvdb.com/banners/series/389250/posters/5feb31ab9cb5f.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/389250/posters/5feb31ab9cb5f.jpg',
    aliases: [
      "2.43: Seiin high school Boys' Volleyball Club",
      '2.43 清陰高校男子バレー部',
      '2.43',
      '2.43: Seiin Koukou Danshi Volley-bu',
      '2.43 清陰高校男子バレー部',
      '2.43: Seiin Koukou Danshi Volley-bu',
      '2.43: Seiin High School Boys Volleyball Club',
      '2.43: Seiin Kōkō Danshi Volley-bu',
      '2.43: Seiin Koukou Danshi Volley-bu',
      '2.43 Seiin Koukou Danshi Volleybu',
      '2.43: Seiin Koukou Danshi Volley-bu',
      '2.43: Seiin Kōkō Danshi Volley-bu',
      '2.43: Seiin Koukou Danshi Volley-bu',
      '2.43: Seiin High School Boys Volleyball Club',
    ],
    tags: ['Drama', 'Slice of Life', 'Sports'],
    tvdbId: 389250,
    title: '2.43: Seiin High School Boys Volleyball Team',
    queryYear: 2021,
    airdate: '2021-01-08T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: '2.43: Seiin High School Boys Volleyball Team',
    originalTitle: '2.43: Seiin High School Boys Volleyball Team',
    status: 'Ended',
  },
  {
    description:
      'Fuutarou Uesugi is a poor, antisocial ace student who one day meets the rich transfer student Itsuki Nakano. They argue but when Uesugi realizes he is to be her tutor, he tries to get on better terms. While trying to do so he meets four other girls.',
    imageUrl: 'https://www.thetvdb.com/banners/posters/5c36da6d195bb.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/5c36da6d195bb.jpg',
    aliases: [
      '五等分の花嫁∬',
      'Gotōbun no Hanayome',
      'Gotoubun no Hanayome',
      '5-toubun no Hanayome',
      'The Five Wedded Brides',
      'Gotōbun no Hanayome ∬',
      'Gotoubun no Hanayome ∬',
      '5-toubun no Hanayome ∬',
      '5-toubun no Hanayome',
      'Gotoubun no Hanayome',
      'The Quintessential Quintuplets',
      'Go-Toubun no Hanayome',
      'Five Equal Brides',
      'The Five Wedded Brides',
    ],
    tags: ['Comedy', 'Drama', 'Romance', 'Slice of Life'],
    tvdbId: 355966,
    title: 'The Quintessential Quintuplets',
    queryYear: 2021,
    airdate: '2019-01-11T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'The Quintessential Quintuplets',
    originalTitle: 'The Quintessential Quintuplets 2',
    status: 'Ended',
  },
  {
    description:
      'The story revolves around "Aikatsu Planet," a virtual world where anyone can assume the role of an avatar and become an adorably cute idol. Mao Otoha, an ordinary first-year student at the private academy Seirei High School, becomes the #1 idol avatar Hana when Hana\'s previous alter ego Meisa Hinata suddenly disappeared. However, Mao\'s new role as the avatar Hana is a secret to everyone else. ',
    imageUrl:
      'https://www.thetvdb.com/banners/series/395400/posters/600b128e8e6ff.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/395400/posters/600b128e8e6ff.jpg',
    aliases: ['아이 엠 스타 플래닛!'],
    tags: ['Music'],
    tvdbId: 395400,
    title: 'Aikatsu Planet!',
    queryYear: 2021,
    airdate: '2021-01-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Aikatsu Planet!',
    originalTitle: 'Aikatsu Planet!',
    status: 'Continuing',
  },
  {
    description:
      'Lingalind is a land enclosed by the Wall. The Wall covers, protects, cultivates, and nurtures the land. One day in Edger, a village on the outskirts of Lingalind, a mysterious man named Back Arrow appears. Arrow has lost his memory, but he claims that all he knows is that "I came from outside the Wall.”',
    imageUrl:
      'https://www.thetvdb.com/banners/v4/series/391465/posters/60716ba1b4227.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/v4/series/391465/posters/60716ba1b4227.jpg',
    aliases: [],
    tags: ['Action', 'Adventure', 'Fantasy', 'Mecha', 'Sci-Fi'],
    tvdbId: 391465,
    title: 'Back Arrow',
    queryYear: 2021,
    airdate: '2021-01-09T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'BACK ARROW',
    originalTitle: 'BACK ARROW',
    status: 'Ended',
  },
  {
    description:
      "The story takes place in a world of civilized anthropomorphic animals with a cultural divide between the carnivores and herbivores. The series takes its name from the in-universe rank of Beastar, an individual of great talent, service, and notoriety. Legosi, a large gray wolf, is a timid and quiet student of Cherryton School where he lives in a dorm with several other carnivorous students including his outgoing Labrador friend, Jack. As a member of the school's drama club, Legosi works as a stagehand and supports the actors of the club headed by the star pupil Louis, a red deer. Out of nowhere, Tem the alpaca is brutally murdered and devoured in the night setting a wave of unease and distrust between the herbivore and carnivore students. At the same time, Legosi has a fateful encounter with Haru, a small dwarf rabbit, and begins developing complex feelings for her.",
    imageUrl:
      'https://www.thetvdb.com/banners/series/361013/posters/5fa1f659b9bbf.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/361013/posters/5fa1f659b9bbf.jpg',
    aliases: ['비스타즈'],
    tags: ['Drama', 'Mystery', 'Psychological', 'Romance', 'Slice of Life'],
    tvdbId: 361013,
    title: 'Beastars',
    queryYear: 2021,
    airdate: '2019-10-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'BEASTARS',
    originalTitle: 'BEASTARS Season 2',
    status: 'Ended',
  },
  {
    description:
      'When a mysterious light suddenly engulfs Earth, humanity is left petrified, frozen in stone. Thousands of years later, the world is teeming with vegetation, and forests have taken the places of cities that once stood proudly. One of the very first to emerge from their stone prison is Taiju Oki, who finds that his good friend, a brilliant young scientist named Senkuu, has been preparing for his awakening. While Taiju wishes to save the girl he loves, Senkuu is determined to figure out the cause behind the strange phenomenon and restore the world to its former glory.',
    imageUrl:
      'https://www.thetvdb.com/banners/v4/series/355774/posters/60930ab8bd11d.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/v4/series/355774/posters/60930ab8bd11d.jpg',
    aliases: [
      'Doctor Stone',
      'Dr. Stone: Stone Wars',
      'ドクターストーン',
      'Dr.STONE STONE WARS',
      'ドクターストーン STONE WARS',
      '新石紀',
      '新石纪',
    ],
    tags: ['Action', 'Adventure', 'Comedy', 'Sci-Fi'],
    tvdbId: 355774,
    title: 'Dr. Stone',
    queryYear: 2021,
    airdate: '2019-07-05T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Dr. STONE: STONE WARS',
    originalTitle: 'Dr. STONE: STONE WARS',
    status: 'Continuing',
  },
  {
    description:
      "2014: Akira Natsume seems to almost have a phobia of electrical devices while also being very good at diagnosing them. He resolves to change himself for the better and get a girlfriend like his older brother did. ...But then Akira suddenly dies in an accident. 16 years later a special policewoman and her android partner retrieve and activate a highly advanced AI and superweapon called EX-ARM and put it into full control of their ship as a last resort. Turns out the AI is actually just Akira's brain!",
    imageUrl:
      'https://www.thetvdb.com/banners/series/382958/posters/5f033cb3e39c0.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/382958/posters/5f033cb3e39c0.jpg',
    aliases: ['EX-ARM', 'Ex-Arm'],
    tags: ['Action', 'Sci-Fi'],
    tvdbId: 382958,
    title: 'Ex-Arm',
    queryYear: 2021,
    airdate: '2021-01-11T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'EX-ARM',
    originalTitle: 'EX-ARM',
    status: 'Ended',
  },
  {
    description:
      'Five years after a mystifying disaster decimates cities across the globe, Seria Morino receives an invitation to join Alice in Theater, a small stage troupe that takes it upon themselves to brighten the world through their performances.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/388739/posters/5feb2c69972e5.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/388739/posters/5feb2c69972e5.jpg',
    aliases: ['Actidol Project'],
    tags: ['Drama', 'Psychological', 'Sci-Fi'],
    tvdbId: 388739,
    title: 'Gekidol',
    queryYear: 2021,
    airdate: '2021-01-05T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Gekidol',
    originalTitle: 'Gekidol',
    status: 'Ended',
  },
  {
    description:
      'Alcohol, smoking, and stress—in the body subjected to these irritants, the cells responsible for maintaining life seem to fight a war that never ends. Due to a severe shortage of workers, Red Blood Cell AA2153 has to quickly learn to deliver oxygen and collect carbon dioxide, even in dangerous conditions. Meanwhile, White Blood Cell U-1196 has to do her part by dealing with germs and viruses during life-threatening situations. In the midst of these crises, they have to work together to keep the body healthy, despite not knowing if their sacrifices will be worthwhile.\r\n\r\nCells at Work! Code Black takes a different approach by showing the grittier side of the jobs our cells perform.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/380402/posters/60233593bfcc1.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/380402/posters/60233593bfcc1.jpg',
    aliases: [
      'Hataraku Saibō Black',
      'Hataraku Saibou Black',
      'Cells at Work! CODE BLACK!',
      'Hataraku Saibou Black',
      'Hataraku Saibou Black',
    ],
    tags: ['Action', 'Drama', 'Sci-Fi'],
    tvdbId: 380402,
    title: 'Cells at Work! Code Black',
    queryYear: 2021,
    airdate: '2021-01-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Cells at Work! CODE BLACK',
    originalTitle: 'Cells at Work! CODE BLACK',
    status: 'Ended',
  },
  {
    description:
      "This is a story about you. A tale about the inside of your body... According to a new study, the human body consists of approximately 37 trillion cells. These cells are hard at work every day within a world that is your body. From the oxygen-carrying red blood cells to the bacteria-fighting white blood cells, get to know the unsung heroes and the drama that unfolds inside of you! It's the oddly relatable and interesting story that is the life of cells! ",
    imageUrl:
      'https://www.thetvdb.com/banners/v4/series/346931/posters/60b606f090e5e.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/v4/series/346931/posters/60b606f090e5e.jpg',
    aliases: [
      'Cells at Work!',
      'Hataraku Saibō',
      'Hataraku Saibou',
      'Cells at Work!!',
      'はたらく細胞（2018）',
      'はたらく細胞!! ',
      'はたらく細胞（2021）',
      'はたらく細胞!! (2021)',
    ],
    tags: ['Action', 'Comedy', 'Sci-Fi'],
    tvdbId: 346931,
    title: 'Cells at Work!',
    queryYear: 2021,
    airdate: '2018-07-08T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Cells at Work!!',
    originalTitle: 'Cells at Work!!',
    status: 'Ended',
  },
  {
    description:
      "What would happen if the most popular girl met the gloomiest boy in the class? Kyoko Hori is good-looking, and top student and popular. But the reality is she's a homebody who goes straight home from school every day to look after the house and her younger brother. One day, a stranger brings her injured brother home... and recognises her.",
    imageUrl:
      'https://www.thetvdb.com/banners/series/388593/posters/5feb3592b0663.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/388593/posters/5feb3592b0663.jpg',
    aliases: [
      'Hori-san to Miyamura-kun',
      'Hori-Miya',
      'Hori-san and Miyamura-kun',
      'Hori-san to Miyamura-kun',
      'ホリミヤ(アニメ)',
      'ホリミヤ(アニメ)',
      'Hori-san to Miyamura-kun (TV)',
    ],
    tags: ['Comedy', 'Romance', 'Slice of Life'],
    tvdbId: 388593,
    title: 'Horimiya',
    queryYear: 2021,
    airdate: '2021-01-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Horimiya',
    originalTitle: 'Horimiya',
    status: 'Ended',
  },
  {
    description:
      'Despite the constant threat of invasion by neighboring countries who covet Hortensia’s fertile lands, Hortensia has long managed to avoid the maelstrom of war thanks to its two main territories, the principalities of Olivier and Camelia, serving as its sword and shield. But on December 5, 767, Camelia suddenly rises in revolt against Hortensia...',
    imageUrl:
      'https://www.thetvdb.com/banners/series/390384/posters/5feb352303335.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/390384/posters/5feb352303335.jpg',
    aliases: ['Horsaga'],
    tags: ['Action', 'Adventure', 'Drama', 'Fantasy'],
    tvdbId: 390384,
    title: 'Hortensia Saga',
    queryYear: 2021,
    airdate: '2021-01-07T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Hortensia SAGA',
    originalTitle: 'Hortensia SAGA',
    status: 'Ended',
  },
  {
    description:
      'Youths aiming to become full-fledged idols enroll in the Étoile Vio School where the students are called IChu. But soon after they begin, Kuma Kocho gets them off to a rocky start with a single phrase...?! As they each work toward their individual goals, their activities as idols make the IChu begin to wonder... "What is an idol?" In their struggle to find an answer, the springtime of the IChu\'s lives is whittled out in glittering moments and flashes of brilliance. Their story begins now!',
    imageUrl:
      'https://www.thetvdb.com/banners/series/394678/posters/5ffca7fac0395.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/394678/posters/5ffca7fac0395.jpg',
    aliases: [
      'I★CHU Étoile Stage',
      'I-Chu: Halfway Through the Idol',
      'IChu: Halfway Through the Idol',
      'I★Chu - Halfway Through the Idol',
      'I★CHU',
    ],
    tags: ['Music'],
    tvdbId: 394678,
    title: 'I★Chu: Halfway Through the Idol',
    queryYear: 2021,
    airdate: '2021-01-06T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'I★CHU',
    originalTitle: 'I★CHU',
    status: 'Ended',
  },
  {
    description:
      'High school student Kotono Nagase moves into a dorm with nine other aspiring idols, who quickly realize it takes more than cute choreography and cute outfits to advance in the idol-ranking VENUS program... where the top spot is held by Kotono’s older sister.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/386353/posters/602a0c9dc16ee.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/386353/posters/602a0c9dc16ee.jpg',
    aliases: ['偶像榮耀', 'アイドリープライド', '아이돌리 프라이드'],
    tags: ['Drama', 'Music', 'Slice of Life', 'Supernatural'],
    tvdbId: 386353,
    title: 'Idoly Pride',
    queryYear: 2021,
    airdate: '2021-01-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Idoly Pride',
    originalTitle: 'Idoly Pride',
    status: 'Ended',
  },
  {
    description:
      "Tomozaki is one of the best gamers in Japan, and in his opinion, the game of real life is one of the worst. No clear-cut rules for success, horribly balanced, and nothing makes sense. But then he meets a gamer who's just as good as him, and she offers to teach him a few exploits...",
    imageUrl:
      'https://www.thetvdb.com/banners/series/388737/posters/5ff91f95d49cc.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/388737/posters/5ff91f95d49cc.jpg',
    aliases: [
      'Bottom-tier Character Tomozaki',
      'tomozaki-koushiki',
      'Jaku-Chara Tomozaki-kun',
      'Bottom-Tier Character Tomozaki',
      'Jaku-Chara Tomozaki-kun',
      'Jaku-Chara Tomozaki-kun',
      'Jakusha Character Tomozaki-kun',
      'The Low Tier Character « Tomozaki-kun »',
      'Yowai Character Tomozaki-kun',
      'Низькорівневий персонаж Томозакі',
      'The Low Tier Character Tomozaki-kun',
      'Yowai Character Tomozaki-kun',
      'Jaku-chara Tomozaki-kun',
      'Trash-Tier Tomozaki-kun',
    ],
    tags: ['Comedy', 'Drama', 'Romance', 'Slice of Life'],
    tvdbId: 388737,
    title: 'Bottom-tier Character Tomozaki',
    queryYear: 2021,
    airdate: '2021-01-08T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Bottom-Tier Character Tomozaki',
    originalTitle: 'Bottom-Tier Character Tomozaki',
    status: 'Ended',
  },
  {
    description:
      'So long as people have hearts, there will be those with worries and concerns. Those hearts are then invaded by something strange, causing them to show strange physical symptoms. These ailments, called "mysterious diseases," exist unseen to most people. Modern medicine offers no cure, but there is one doctor who fights these diseases along with his pupils. His name is Ramune. He looks nothing like a doctor, is foul-mouthed, and does whatever he pleases, but he has the ability to pinpoint the cause of the troubles hidden deep within his patients\' hearts and cure their mysterious diseases.',
    imageUrl:
      'https://www.thetvdb.com/banners/v4/series/391365/posters/609d7d6b4827a.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/v4/series/391365/posters/609d7d6b4827a.jpg',
    aliases: ['Dr. Ramune', 'Kai Byoui Ramune', 'Kai Byoui Ramune'],
    tags: ['Drama', 'Psychological', 'Supernatural'],
    tvdbId: 391365,
    title: 'Dr. Ramune: Mysterious Disease Specialist',
    queryYear: 2021,
    airdate: '2021-01-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Dr. Ramune -Mysterious Disease Specialist-',
    originalTitle: 'Dr. Ramune -Mysterious Disease Specialist-',
    status: 'Ended',
  },
  {
    description:
      'When a series of animal bodies that rot away after a single night begin appearing in a remote mountain village, Inugami, a detective from Tokyo who specializes in the occult, is called to investigate.\r\n\r\nWhile working the case, he befriends a strange boy who works in the field every day instead of going to school. Shunned by his peers and nicknamed "Dorota-bou" after a yokai that lives in the mud, he helps Inugami uncover the truth behind the killings—but supernatural forces are at work, and while Dorota-bou is just a nickname, it might not be the only thing about the boy that isn\'t human.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/390382/posters/5f8d571980931.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/390382/posters/5f8d571980931.jpg',
    aliases: [
      'Kemono Jihen',
      'Casi Mostruosi',
      'Kemono Jihen',
      'Monster Incidents',
    ],
    tags: ['Action', 'Drama', 'Mystery', 'Supernatural'],
    tvdbId: 390382,
    title: 'Kemono Jihen',
    queryYear: 2021,
    airdate: '2021-01-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Kemono Jihen',
    originalTitle: 'Kemono Jihen',
    status: 'Ended',
  },
  {
    description:
      "I, the protagonist, was just an ordinary high school girl, but suddenly I was reincarnated as a spider monster in a fantasy world. Not only that, but I awakened in a dungeon filled with vicious monsters. Armed with only my human knowledge and my overwhelming positivity, I'm forced to use spiderwebs and traps to defeat far stronger monsters just to stay alive... So begins the labyrinth survival story of a girl with incredible mental strength living as one of the lowest-ranked beasts!",
    imageUrl:
      'https://www.thetvdb.com/banners/v4/series/377902/posters/60705a5193e57.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/v4/series/377902/posters/60705a5193e57.jpg',
    aliases: [
      'Kumo Desu ga, Nani ka?',
      "So I'm a Spider, So What?",
      'Kumo desu ga, Nani ka?',
      'Kumo Desu ga, Nanika?',
      'Kumo desu ga, Nani ka?',
      'KumoDesu',
      'Kumo Kumo Kumo Spider',
      "So I'm a Spider, So What?",
    ],
    tags: ['Action', 'Adventure', 'Comedy', 'Fantasy', 'Mystery'],
    tvdbId: 377902,
    title: "So I'm a Spider, So What?",
    queryYear: 2021,
    airdate: '2021-01-08T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: "So I'm a Spider, So What?",
    originalTitle: "So I'm a Spider, So What?",
    status: 'Ended',
  },
  {
    description:
      "One day, while playing the online game Elder Tales, 30,000 players suddenly find themselves trapped in another world. There, eight-year veteran gamer Shiroe also gets left behind. The trapped players are still alive, but they remain in combat with the monsters. The players don't understand what has happened to them, and they flee to Akiba, the largest city in Tokyo, where they are thrown into chaos. Once proud of his loner lifestyle, Shiroe forms a guild called Log Horizon with his old friend Naotsugu, female assassin Akatsuki and others.",
    imageUrl: 'https://www.thetvdb.com/banners/posters/272128-2.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/272128-2.jpg',
    aliases: [
      'Log Horizon: Entaku Houkai',
      'Log Horizon: Entaku Houkai',
      'Log Horizon: A Queda da Távola Redonda',
      'Rogu Horaizun',
      'Log Horizon 2',
      'Log Horizon 3',
      'Log Horizon II',
      'Log Horizon III',
      'Log Horizon: Destruction of the Round Table',
      'Log Horizon: Entaku Hōkai',
      'Log Horizon: Entaku Houkai',
      'Лоґ Горизонт',
      'Лог Горизонт',
    ],
    tags: ['Action', 'Adventure', 'Comedy'],
    tvdbId: 272128,
    title: 'Log Horizon',
    queryYear: 2021,
    airdate: '2013-10-05T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Log Horizon: Destruction of the Round Table',
    originalTitle: 'Log Horizon: Destruction of the Round Table',
    status: 'Ended',
  },
  {
    description:
      'Kiyo and Sumire came to Kyoto from Aomori Prefecture, dreaming of becoming maiko. But after an unexpected turn of events, Kiyo starts working as the live-in cook at the Maiko House. Their story unfolds in Kagai, the Geiko and maiko district in Kyoto, alongside their housemate maikos. Kiyo nourishes them daily with her homecooked meals, and Sumire strives toward her promising future as the once-in-a-century maiko.',
    imageUrl:
      'https://www.thetvdb.com/banners/v4/series/397425/posters/608811d022ba4.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/v4/series/397425/posters/608811d022ba4.jpg',
    aliases: [
      'Kiyo em Kyoto: Da Casa Maiko ',
      'Kiyo in Kyoto: From the Maiko House',
      'Maiko-san Chi no Makanai-san',
      'Maiko-san Chi no Makanai-san',
      'The Caterer at the Maiko Manor',
      'Kiyo in Kyoto - From the Maiko House',
    ],
    tags: ['Slice of Life'],
    tvdbId: 397425,
    title: 'Kiyo in Kyoto: From the Maiko House',
    queryYear: 2021,
    airdate: '2021-02-25T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Kiyo in Kyoto: From the Maiko House',
    originalTitle: 'Kiyo in Kyoto: From the Maiko House',
    status: 'Continuing',
  },
  {
    description:
      'Orphen is a powerful sorcerer who is notoriously lazy. Everything changes when he finds a way to save his sis, who was turned into a dragon during their days at magic academy. Betrayed by friends who refused to help, Orphen will stop at nothing to track her down, even if he has to go it alone.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/372939/posters/62044009.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/372939/posters/62044009.jpg',
    aliases: [
      'Sorcerous Stabber Orphen - Hagure Tabi',
      '魔術士オーフェンはぐれ旅 キムラック編',
      'Majutsushi Orphen Hagure Tabi',
      'Majutsushi Orphen Haguretabi',
      'Orphen',
      'Sorcerous Stabber Orphen',
      'Orphen',
    ],
    tags: ['Action', 'Adventure', 'Fantasy'],
    tvdbId: 372939,
    title: 'Sorcerous Stabber Orphen',
    queryYear: 2021,
    airdate: '2020-01-07T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Sorcerous Stabber Orphen:',
    originalTitle: 'Sorcerous Stabber Orphen: Battle of Kimluck',
    status: 'Ended',
  },
  {
    description:
      'Killed while saving a stranger from a traffic collision, a 34-year-old NEET is reincarnated into a world of magic as Rudeus Greyrat, a newborn baby. With knowledge, experience, and regrets from his previous life retained, Rudeus vows to lead a fulfilling life and not repeat his past mistakes.\r\n\r\nNow gifted with a tremendous amount of magical power and the mind of a grown adult, Rudeus is seen as a genius in the making by his new parents. Soon, he finds himself studying under powerful warriors, such as his swordsman father and a mage named Roxy Migurdia—all in order to hone his apparent talents. But despite his innocent exterior, Rudeus is still a perverted otaku, who uses his wealth of knowledge to make moves on women who would have been out of reach in his past life.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/371310/posters/5fe3501788cc3.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/371310/posters/5fe3501788cc3.jpg',
    aliases: [
      'Jobless Reincarnation: I Will Seriously Try If I Go To Another World',
      'Mushoku Tensei: Isekai Ittara Honki Dasu',
      'Jobless Reincarnation: I Will Seriously Try If I Go To Another World',
      'Mushoku Tensei',
      'Mushoku Tensei: Isekai Ittara Honki Dasu',
      'Mushoku Tensei: Isekai Ittara Honki Dasu',
      ' 无职转生',
      'Mushoku Tensei: Isekai Ittara Honki Dasu',
      'Mushoku Tensei',
      'Jobless Reincarnation',
      'Jobless Reincarnation: I Will Seriously Try If I Go to Another World',
      'Reencarnação sem uma Função: Se Estou num Outro Mundo, Irei com Tudo',
    ],
    tags: ['Adventure', 'Drama', 'Ecchi', 'Fantasy'],
    tvdbId: 371310,
    title: 'Mushoku Tensei: Jobless Reincarnation',
    queryYear: 2021,
    airdate: '2021-01-11T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Mushoku Tensei: Jobless Reincarnation',
    originalTitle: 'Mushoku Tensei: Jobless Reincarnation',
    status: 'Continuing',
  },
  {
    description:
      'The legend of the confrontation between the Seven Deadly Sins and the Holy Knights.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/284131/posters/601d611f8f7d4.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/284131/posters/601d611f8f7d4.jpg',
    aliases: [
      'Nanatsu no Taizai : Seisen no Shirushi',
      '七つの大罪 聖戦の予兆',
      'Nanatsu in Taizai: Imashime no Fukkatsu',
      '七つの大罪 戒めの復活',
      '七つの大罪 神々の逆鱗',
      'Nanatsu no Taizai: Kamigami no Gekirin',
      'Nanatsu no Taizai',
      'The Seven Deadly Sins',
      'Os Sete Pecados Mortais',
      '七原罪',
      'Nanatsu no Taizai',
      'Nanatsu no Taizai -Seisen no Shirushi-',
      'The Seven Deadly Sins -Signs of Holy War-',
      'Seven Deadly Sins: Signs of Holy War',
      'The Seven Deadly Sins: Signs of Holy War',
      'The Seven Deadly Sins: Revival of The Commandments',
      'Nanatsu in Taizai: Imashime no Fukkatsu',
      'The Seven Deadly Sins: Wrath of the Gods',
      'Nanatsu no Taizai: Kamigami no Gekirin',
    ],
    tags: ['Action', 'Adventure', 'Comedy', 'Ecchi', 'Fantasy', 'Supernatural'],
    tvdbId: 284131,
    title: 'The Seven Deadly Sins',
    queryYear: 2021,
    airdate: '2014-10-05T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'The Seven Deadly Sins:',
    originalTitle: "The Seven Deadly Sins: Dragon's Judgment",
    status: 'Ended',
  },
  {
    description:
      'Elementary school student Ichijou Hotaru has moved with her parents from Tokyo to the middle of the country. Now she must adapt to her new school, where there are a total of 5 students in the same class who range through elementary and middle school ages. Join their everyday adventures in the countryside. ',
    imageUrl: 'https://www.thetvdb.com/banners/posters/272316-1.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/272316-1.jpg',
    aliases: [
      '悠悠哉哉少女日和',
      'のんのんびより のんすとっぷ',
      'Non Non Biyori Repeat',
      'Non Non Biyori Nonstop',
      'Деревенская глубинка',
      'Глухомань',
    ],
    tags: ['Comedy', 'Slice of Life'],
    tvdbId: 272316,
    title: 'Non Non Biyori',
    queryYear: 2021,
    airdate: '2013-10-08T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Non Non Biyori Nonstop',
    originalTitle: 'Non Non Biyori Nonstop',
    status: 'Ended',
  },
  {
    description:
      "The Hidden Dungeon is a place of legend where rare treasures and items are hidden. Nor, the third son of an impoverished noble family who's lost the one job offer he had, was lucky enough to hear about this dungeon. He then acquires a skill that allows him to create, bestow, and edit skills... and in order to use it, he needs to accumulate points by carrying out such tasks as eating delicious meals and doing sexual things with alluring members of the opposite sex.",
    imageUrl:
      'https://www.thetvdb.com/banners/series/388006/posters/5ff205644a3cd.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/388006/posters/5ff205644a3cd.jpg',
    aliases: [
      'Ore dake Haireru Kakushi Dungeon - Kossori Kitaete Sekai Saikyou',
      'Ore dake Haireru Kakushi Dungeon',
      'Special Training in the Secret Dungeon',
      'Ore dake Haireru Kakushi Dungeon',
      'Ore dake Haireru Kakushi Dungeon: Kossori Kitaete Sekai Saikyō',
    ],
    tags: ['Action', 'Adventure', 'Comedy', 'Ecchi', 'Fantasy', 'Romance'],
    tvdbId: 388006,
    title: 'The Hidden Dungeon Only I Can Enter',
    queryYear: 2021,
    airdate: '2021-01-09T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'The Hidden Dungeon Only I Can Enter',
    originalTitle: 'The Hidden Dungeon Only I Can Enter',
    status: 'Ended',
  },
  {
    description:
      'In the wake of a rebellion in the Akatsuki Special Ward of Tokyo, agents known as the Scard rise up to become the protectors of peace. With Divine Tattoos that each possess unique powers, they’ll have to fight to preserve their own definitions of justice.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/392196/posters/5feb2f21cdf11.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/392196/posters/5feb2f21cdf11.jpg',
    aliases: [
      'Project Scard : Scar on the Praeter',
      'PROJECT SCARD プレイタの傷',
      'PROJECT SCARD',
      'Project Scard: Scar on the Praeter',
      'Project Scard: Praeter no Kizu',
      'Project Scard: Scar on the Praeter',
    ],
    tags: ['Action', 'Fantasy', 'Sci-Fi'],
    tvdbId: 392196,
    title: 'Scar on the Praeter',
    queryYear: 2021,
    airdate: '2021-01-09T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Scar on the Praeter',
    originalTitle: 'Scar on the Praeter',
    status: 'Ended',
  },
  {
    description:
      'Shortly after being summoned to a new world, Subaru Natsuki and his new female companion are brutally murdered. But then he awakes to find himself in the same alley, with the same thugs, the same girl, and the day begins to repeat.',
    imageUrl:
      'https://www.thetvdb.com/banners/v4/series/305089/posters/60aa37d7c847b.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/v4/series/305089/posters/60aa37d7c847b.jpg',
    aliases: [
      'Re: Жизнь в альтернативном мире с нуля',
      'Re:ゼロから始める異世界生活 新編集版',
      'REZERO',
      'RE ZERO',
      "Director's Cut",
      'Edição do Diretor',
      'Re:Zero kara Hajimeru Isekai Seikatsu',
      'Re:從零開始的異世界生活',
      '从零开始的异世界生活',
      'Re: Zero Kara Hajimeru Isekai Seikatsu',
      'Re: Life in a different world from zero',
    ],
    tags: [
      'Action',
      'Adventure',
      'Drama',
      'Fantasy',
      'Psychological',
      'Romance',
      'Thriller',
    ],
    tvdbId: 305089,
    title: 'Re:ZERO -Starting Life in Another World-',
    queryYear: 2021,
    airdate: '2016-04-04T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Re:ZERO -Starting Life in Another World-',
    originalTitle: 'Re:ZERO -Starting Life in Another World- Season 2 Part 2',
    status: 'Ended',
  },
  {
    description:
      'During the 19th century China, the protagonist, Liu Maoxing, wins the title of Super Chef and is the youngest to do so in history. His master, Zhou Yu, suggests that he broaden his skills as a chef even more, so he goes on a journey around China with his friends Shirou and Meili. After returning, he also teams up with Xie Lu and Lei En to fight the Underground Cooking Society. He then learns the secret about the 8 Legendary Cooking Tools. In the past, Mao’s mother, Bei, had wished for everyone’s happiness and fought against the Underground Cooking Society. In order to continue his mother’s wishes and protect the Legendary Cooking Utensils from the Underground Cooking Society, Mao and his friends go on a journey...',
    imageUrl:
      'https://www.thetvdb.com/banners/series/370891/posters/62021555.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/370891/posters/62021555.jpg',
    aliases: [
      '真・中华一番！',
      'Shin Chuuka Ichiban!',
      'Shin Chuuka Ichiban!',
      'New Cooking Master Boy',
      '요리왕 비룡 더 마스터!',
      '진 중화일미!',
      'Shin Chūka Ichiban!',
      'Shin Chuuka Ichiban!',
    ],
    tags: ['Comedy'],
    tvdbId: 370891,
    title: 'True Cooking Master Boy',
    queryYear: 2021,
    airdate: '2019-10-12T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'True Cooking Master Boy',
    originalTitle: 'True Cooking Master Boy Season 2',
    status: 'Ended',
  },
  {
    description:
      'After his hometown is destroyed and his mother is killed, young Eren Yeager vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.\r\n',
    imageUrl: 'https://www.thetvdb.com/banners/posters/267440-3.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/267440-3.jpg',
    aliases: [
      '進撃の巨人 (2013)',
      'Вторжение Гигантов',
      'Вторжение Титанов',
      'Titana saldırı',
      'titan saldırısı',
      'attack on titan',
      'Shingeki no Kyojin',
      'SNK',
      'Ataque Dos Titãs',
      'Ataque Dos Titãs',
      'Attack on Titan',
      'Shingeki no Kyojin',
      'Attack on Titan',
      'Útok na Titány',
      'Útok na Titánov',
      'Útok Titánov',
      'Útok na Titáni',
      'Útok na Titány',
      'Útok titánů',
      'Útok na Titani',
      'Útok na Titany',
    ],
    tags: ['Action', 'Drama', 'Fantasy', 'Mystery'],
    tvdbId: 267440,
    title: 'Attack on Titan',
    queryYear: 2021,
    airdate: '2013-04-07T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Attack on Titan',
    originalTitle: 'Attack on Titan Final Season',
    status: 'Continuing',
  },
  {
    description:
      '"All stars" season of Show by Rock!! featuring all the bands from previous seasons.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/389227/posters/5f712d0cd2863.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/389227/posters/5f712d0cd2863.jpg',
    aliases: ['ショウバイロック!!スターズ!!', '쇼 바이 락!! 스타즈!!'],
    tags: ['Music'],
    tvdbId: 389227,
    title: 'Show By Rock!! Stars!!',
    queryYear: 2021,
    airdate: '2021-01-07T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Show by Rock!! Stars!!',
    originalTitle: 'Show by Rock!! Stars!!',
    status: 'Ended',
  },
  {
    description:
      '"S" is a dangerous, top secret, no-holds-barred downhill skateboarding race down an abandoned mine. When avid skateboarder Reki takes Langa to the mountain where "S" is held, Langa, who’s never been on a skateboard in his life, finds himself sucked into the world of "S" and...?!',
    imageUrl:
      'https://www.thetvdb.com/banners/series/388858/posters/5feb2fbc07042.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/388858/posters/5feb2fbc07042.jpg',
    aliases: [
      'SK Eight',
      'SK8',
      'SK8 the Infinity',
      'SK8',
      'SK∞ the infinity',
      'SK∞',
      'SK Eight',
    ],
    tags: ['Action', 'Comedy', 'Drama', 'Sports'],
    tvdbId: 388858,
    title: 'SK8 the Infinity',
    queryYear: 2021,
    airdate: '2021-01-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'SK8 the Infinity',
    originalTitle: 'SK8 the Infinity',
    status: 'Ended',
  },
  {
    description:
      'Kensei Maeshima left figure skating behind, now only using his athleticism to help several high school teams. But his rival announces a shift to a team sport, bringing a kid familiar with Kensei’s past to offer him an invite to the world of skate-leading.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/373131/posters/5feb34600917d.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/373131/posters/5feb34600917d.jpg',
    aliases: ['Skate Leading Stars'],
    tags: ['Drama', 'Sports'],
    tvdbId: 373131,
    title: 'Skate-Leading☆Stars',
    queryYear: 2021,
    airdate: '2021-01-10T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Skate-Leading Stars',
    originalTitle: 'Skate-Leading Stars',
    status: 'Ended',
  },
  {
    description:
      'In an unplanned field trip, Riko is transported to an alternate Japan where metal-based life forms known as Mimesis ravage the world. Only girls equipped with LBX armored weaponry can stand up to this scourge. Joined by four other displaced young women, Riko will have to adapt to save humanity. The hope of a planet now rests on these heavy metal soldiers who desire one wish—to return home again!',
    imageUrl:
      'https://www.thetvdb.com/banners/series/391883/posters/5feb33cad5505.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/391883/posters/5feb33cad5505.jpg',
    aliases: [
      'LBX Girls',
      'Sōkō Musume Senki',
      'Soukou Musume Senki',
      'Armored Girls',
      'Soukou Musume Senki',
    ],
    tags: ['Action', 'Mecha', 'Sci-Fi'],
    tvdbId: 391883,
    title: 'LBX Girls',
    queryYear: 2021,
    airdate: '2021-01-07T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'LBX Girls',
    originalTitle: 'LBX Girls',
    status: 'Ended',
  },
  {
    description:
      'Lloyd is a novice adventurer whose dream is to discover "true strength" in the capital he\'s always admired, despite growing up with neighbors who always considered him weak. The story starts with him departing from his hometown, which just so happens to be located right next to...one of the most dangerous dungeons in the world?! Lloyd may think of himself as powerless, but when he goes to the city that serves as the starter town for adventurers, the difference between him and everyone else couldn\'t be starker!',
    imageUrl:
      'https://www.thetvdb.com/banners/series/386933/posters/5feb3076cc6b6.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/386933/posters/5feb3076cc6b6.jpg',
    aliases: [
      'Tatoeba Last Dungeon Mae no Mura no Shōnen ga Joban no Machi de Kurasu Yō na Monogatari',
      'Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari',
      'LasDan',
      'Suppose a Kid From the Last Dungeon Boonies Moved to a Starter Town?',
      'Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari',
      'たとえばらすとだんじょんまえのむらのしょうねんがじょばんのまちでくらすようなものがたり',
      'たとえばラストダンジョン前の村',
      'Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu You na Monogatari',
      'Suppose a Kid From the Last Dungeon Boonies Moved to a Starter Town',
      'Lasdan',
    ],
    tags: ['Adventure', 'Comedy', 'Fantasy'],
    tvdbId: 386933,
    title:
      'Suppose a Kid From the Last Dungeon Boonies Moved to a Starter Town?',
    queryYear: 2021,
    airdate: '2021-01-04T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery:
      'Suppose a Kid from the Last Dungeon Boonies moved to a starter town?',
    originalTitle:
      'Suppose a Kid from the Last Dungeon Boonies moved to a starter town?',
    status: 'Ended',
  },
  {
    description:
      "I made the light, the water, and the earth below. Now it's time to make the life that dwells upon it. Actually... that sounds like a giant headache, so I'll contract it out! Heaven's Design Team is an agency that creates made-to-order life forms for their client, God. Why does this life form look like that? Why does this life form live this way? Watch the trials and successes of the designers and engineers forced to breathe life into God's absurd requests!",
    imageUrl:
      'https://www.thetvdb.com/banners/series/392212/posters/5feb382157d61.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/392212/posters/5feb382157d61.jpg',
    aliases: [
      'Tenchi Souzou Design-bu',
      'Tenchisozo Design Bu',
      'Tenchi Sōzō Design-bu',
      'Tenchi Souzou Design-bu',
      'Tendebu',
    ],
    tags: ['Comedy', 'Fantasy', 'Slice of Life'],
    tvdbId: 392212,
    title: "Heaven's Design Team",
    queryYear: 2021,
    airdate: '2021-01-07T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Heaven’s Design Team',
    originalTitle: 'Heaven’s Design Team',
    status: 'Ended',
  },
  {
    description:
      '37-year-old corporate worker Mikami Satoru is stabbed by a random killer, and is reborn to an alternate world. But he turns out to be reborn a slime! Thrown into this new world with the name Rimuru Tempest, he begins his quest to create a world that’s welcoming to all races. Broken free from ordinary, stale past life, his fresh adventure in a fantasy world as a slime monster with unique abilities begins.',
    imageUrl: 'https://www.thetvdb.com/banners/posters/5bb2b28057ade.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/5bb2b28057ade.jpg',
    aliases: [
      'Slime Isekai',
      'TenSura',
      'Tensei Slime',
      'Tensei Shitara Slime Datta Ken',
      'My Reincarnation as a Slime',
      'Regarding Reincarnated to Slime',
      '転生したらスライムだった件 (2020)',
      '転生したらスライムだった件 第2期',
      '転生したらスライムだった件 第2期 第1部',
      'Tensei Shitara Slime Datta Ken',
      'TenSura',
      'That Time I Got Reincarnated as a Slime',
      'Tensei Shitara Slime Datta Ken',
      'That Time I Got Reincarnated as a Slime',
      'TenSura',
      'That Time I Got Reincarnated as a Slime',
      'Tensei Shitara Slime Datta Ken',
    ],
    tags: ['Action', 'Adventure', 'Comedy', 'Fantasy'],
    tvdbId: 352408,
    title: 'That Time I Got Reincarnated as a Slime',
    queryYear: 2021,
    airdate: '2018-10-02T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'That Time I Got Reincarnated as a Slime',
    originalTitle: 'That Time I Got Reincarnated as a Slime Season 2',
    status: 'Continuing',
  },
  {
    description:
      "Manatsu Natsuumi is a first-year junior high school student born and raised on a small island. On the day she moves from the island, She meets Laura, a mermaid girl who has come to the earth alone in search of the legendary warrior, PreCure. Laura's hometown, Grand Ocean, is attacked by a witch who lives in the dark depths of the ocean, and all of their motivational power is taken away. It is said that if the motivational power of humans is also taken away, the world will be in deep trouble. Laura is captured by the witch's servant, and Manatsu transforms into Cure Summer to save her.",
    imageUrl:
      'https://www.thetvdb.com/banners/v4/series/392944/posters/604515c6c6d94.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/v4/series/392944/posters/604515c6c6d94.jpg',
    aliases: [
      'Tropical-Rouge! PreCure',
      'Tropical-Rouge! Pretty Cure',
      '트로피컬 루즈! 프리큐어',
      '트로피컬-루즈! 프리큐어',
      'Tropical-Rouge! Pretty Cure',
      'Tropical-Rouge! Pretty Cure',
      'Tropical-Rouge! Pretty Cure (2021)',
    ],
    tags: ['Action', 'Comedy', 'Fantasy', 'Mahou Shoujo'],
    tvdbId: 392944,
    title: 'Tropical-Rouge! Precure',
    queryYear: 2021,
    airdate: '2021-02-28T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Tropical-Rouge! Pretty Cure',
    originalTitle: 'Tropical-Rouge! Pretty Cure',
    status: 'Continuing',
  },
  {
    description:
      'This is a tale of a world where "horse girls" with glorious names and incredible running abilities live alongside humanity.\r\n\r\nHorse girl Special Week has moved from the country to the city to attend Tracen Academy. There, she and her classmates compete to win the Twinkle Series and earn the title of "Japan’s #1 Horse Girl."',
    imageUrl: 'https://www.thetvdb.com/banners/posters/344220-3.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/344220-3.jpg',
    aliases: [
      'ウマ娘 プリティーダービー Season 2',
      'Uma Musume: Pretty Derby',
      '赛马娘',
    ],
    tags: ['Drama', 'Slice of Life', 'Sports'],
    tvdbId: 344220,
    title: 'Umamusume: Pretty Derby',
    queryYear: 2021,
    airdate: '2018-04-02T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Umamusume: Pretty Derby Season 2',
    originalTitle: 'Umamusume: Pretty Derby Season 2',
    status: 'Ended',
  },
  {
    description:
      'Friendless college girl Sorawo finds a door to another world one day - a strangely post-apocalyptic-feeling Otherside with serene emptiness, which becomes her new “special place.” There, she meets one other human, the beautiful and independent Toriko, and they explore the abandoned Otherside together.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/388381/posters/5feb3322f27fa.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/388381/posters/5feb3322f27fa.jpg',
    aliases: [
      'herside Picnic',
      'Urasekai Picnic',
      'Urasekai Picnic',
      'Otherside Picnic',
      'Urasekai Picnic',
      'Ura Sekai Picnic',
    ],
    tags: ['Adventure', 'Fantasy', 'Mystery', 'Sci-Fi'],
    tvdbId: 388381,
    title: 'Otherside Picnic',
    queryYear: 2021,
    airdate: '2021-01-04T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'Otherside Picnic',
    originalTitle: 'Otherside Picnic',
    status: 'Ended',
  },
  {
    description:
      "The project's story is set in the city of Ōarai in Ibaraki prefecture, and centers on Masaki Hinaoka, who befriends transfer student Shō Akitsuki before the summer break, and ends up getting hooked on surfing. Through the sport, Masaki will get to know new friends, and will also drift apart from them in his journey to adulthood.",
    imageUrl:
      'https://www.thetvdb.com/banners/series/393243/posters/5fd39aea61191.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/393243/posters/5fd39aea61191.jpg',
    aliases: [
      "WAVE!!: Let's Go Surfing!!  (TV)",
      'WAVE!!: Surfing Yappe!! (TV)',
      'WAVE!!: Surfing Yappe!!',
      'WAVE!!: サーフィンやっぺ!! TV',
      'WAVE!!: Surfing Yappe!! TV',
      'WAVE!! Surfing Yappe!!',
      "Wave!! Let's Go Surfing!!",
    ],
    tags: ['Slice of Life', 'Sports'],
    tvdbId: 393243,
    title: "WAVE!!: Let's Go Surfing!!",
    queryYear: 2021,
    airdate: '2021-01-11T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: "WAVE!! -Let's go surfing!!- (TV)",
    originalTitle: "WAVE!! -Let's go surfing!!- (TV)",
    status: 'Ended',
  },
  {
    description:
      'In the popular game WIXOSS, there are special cards called LRIGs that few players know about—cards that possess personalities and wills of their own. Ruko is a teenage girl who just found one of these rare cards. Now, she can use her LRIG to battle in a strange, dark plane of existence. If she wins, her wishes will be granted—but what happens if she loses?',
    imageUrl: 'https://www.thetvdb.com/banners/posters/317206-1.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/317206-1.jpg',
    aliases: [
      'Lostorage Conflated WIXOSS ',
      '失忆融合WIXOSS',
      'Lostorage Incited WIXOSS',
      'Lostorage Conflated WIXOSS',
    ],
    tags: ['Music', 'Sci-Fi'],
    tvdbId: 317206,
    title: 'Lostorage incited WIXOSS',
    queryYear: 2021,
    airdate: '2016-10-08T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'WIXOSS',
    originalTitle: 'WIXOSS DIVA(A)LIVE',
    status: 'Ended',
  },
  {
    description:
      'After the suicide of her best friend, Ai withdraws from the world. One night, she happens to meet a mysterious figure, and is urged into buying an egg—a Wonder Egg. Now whenever Ai falls asleep, a girl emerges from the egg, and the worlds of dreams and reality begin to collide—and with this, a chance of saving her friend.',
    imageUrl:
      'https://www.thetvdb.com/banners/series/390028/posters/5feb34bedf494.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/390028/posters/5feb34bedf494.jpg',
    aliases: ['Wonder Egg Priority'],
    tags: [
      'Action',
      'Drama',
      'Fantasy',
      'Mystery',
      'Psychological',
      'Thriller',
    ],
    tvdbId: 390028,
    title: 'Wonder Egg Priority',
    queryYear: 2021,
    airdate: '2021-01-13T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'WONDER EGG PRIORITY',
    originalTitle: 'WONDER EGG PRIORITY',
    status: 'Ended',
  },
  {
    description:
      "A gate to another dimension has burst open, and from it emerge gigantic invincible creatures that threaten all of humanity. Earth's only defense is a mysterious group of warriors who have co-opted the alien technology in order to fight back!",
    imageUrl:
      'https://www.thetvdb.com/banners/series/283934/posters/5fb0fcc5c29e7.jpg',
    posterUrl:
      'https://www.thetvdb.com/banners/series/283934/posters/5fb0fcc5c29e7.jpg',
    aliases: [],
    tags: ['Action', 'Sci-Fi'],
    tvdbId: 283934,
    title: 'World Trigger',
    queryYear: 2021,
    airdate: '2014-10-05T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'World Trigger',
    originalTitle: 'World Trigger 2nd Season',
    status: 'Continuing',
  },
  {
    description:
      'A group of the smartest kids at a seemingly perfect orphanage uncover its dark truth when they break a rule to never leave the orphanage grounds. Once the truth is discovered, they begin to plan an escape to save all of the children.',
    imageUrl: 'https://www.thetvdb.com/banners/posters/5c04709d4538a.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/5c04709d4538a.jpg',
    aliases: [
      'Yakusoku no Neverland',
      'Обещанная Страна Грез',
      'TPN',
      'Yakusoku no Neverland',
      'نيفرلاند الموعودة (2019)',
      'Yakusoku no Neverland',
      'The Promised Neverland (2019)',
    ],
    tags: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Horror'],
    tvdbId: 348002,
    title: 'The Promised Neverland',
    queryYear: 2021,
    airdate: '2019-01-11T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'The Promised Neverland',
    originalTitle: 'The Promised Neverland Season 2',
    status: 'Ended',
  },
  {
    description:
      "Nadeshiko, a high school student who had moved from Shizuoka to Yamanashi, decides to see the famous, 1000 yen-bill-featured Mount Fuji. Even though she manages to bike all the way to Motosu, she's forced to turn back because of worsening weather. Unable to set her eyes on her goal, she faints partway to her destination. When she wakes up, it's night, in a place she's never been before, with no way of knowing how to get home. Nadeshiko is saved when she encounters Rin, a girl who is out camping by herself. This outdoorsy girls story begins with this first encounter between Nadeshiko and Rin.",
    imageUrl: 'https://www.thetvdb.com/banners/posters/330692-5.jpg',
    posterUrl: 'https://www.thetvdb.com/banners/posters/330692-5.jpg',
    aliases: [
      'مخيم الغرفة',
      'Yuru Camp',
      'Yuru Camp△',
      'YuruCamp',
      'Yurukyan',
      'Heya Camp',
      'Heya Camp△',
      'Room Camp',
      'Laid Back Camp',
      'Comfy Camp',
      '방캠△',
      '실내캠핑△',
      '유루캠프',
      'Laid-Back Camp',
      'Room Camp',
      'Heya Camp △',
      'Cantinho do Acampamento △',
      'Лагерь на свежем воздухе',
      ' Уютный поход',
      'ゆるキャン',
      'ゆるキャン（アニメ）',
      'ゆるキャン△（アニメ）',
      'Yuru Camp: Heya Kyan',
      'へやキャン ',
      'ゆるキャン: へやキャン',
    ],
    tags: ['Comedy', 'Slice of Life'],
    tvdbId: 330692,
    title: 'Laid-Back Camp',
    queryYear: 2021,
    airdate: '2018-01-04T00:00:00.000Z',
    season: 'WINTER',
    matchedQuery: 'LAID-BACK CAMP',
    originalTitle: 'LAID-BACK CAMP SEASON2',
    status: 'Ended',
  },
];
